-- liquibase formatted sql

-- changeset panch:1761085684742-1
CREATE TABLE address
(
    address_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alias       VARCHAR(255),
    street      VARCHAR(255),
    city        VARCHAR(255),
    country     VARCHAR(255),
    postal_code VARCHAR(255),
    user_id     BIGINT,
    CONSTRAINT pk_address PRIMARY KEY (address_id)
);

-- changeset panch:1761085684742-2
CREATE TABLE attribute_option
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value                 VARCHAR(255),
    category_attribute_id BIGINT,
    CONSTRAINT pk_attribute_option PRIMARY KEY (id)
);

-- changeset panch:1761085684742-3
CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description TEXT                                    NOT NULL,
    is_active   BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

-- changeset panch:1761085684742-4
CREATE TABLE category_attribute
(
    category_attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                            NOT NULL,
    input_type            VARCHAR(255)                            NOT NULL,
    is_required           BOOLEAN,
    category_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_category_attribute PRIMARY KEY (category_attribute_id)
);

-- changeset panch:1761085684742-5
CREATE TABLE order_item
(
    order_item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity          INTEGER,
    price_at_purchase DECIMAL,
    order_id          BIGINT,
    product_id        BIGINT,
    CONSTRAINT pk_order_item PRIMARY KEY (order_item_id)
);

-- changeset panch:1761085684742-6
CREATE TABLE orders
(
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number VARCHAR(255)                            NOT NULL,
    total_amount DECIMAL                                 NOT NULL,
    status       VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    address_id   BIGINT                                  NOT NULL,
    user_id      BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

-- changeset panch:1761085684742-7
CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

-- changeset panch:1761085684742-8
CREATE TABLE product
(
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    TEXT,
    price          DECIMAL,
    stock_quantity INTEGER,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    active         BOOLEAN,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

-- changeset panch:1761085684742-9
CREATE TABLE product_attribute
(
    product_attribute_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value                 VARCHAR(255)                            NOT NULL,
    product_id            BIGINT                                  NOT NULL,
    category_attribute_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_attribute PRIMARY KEY (product_attribute_id)
);

-- changeset panch:1761085684742-10
CREATE TABLE product_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id  BIGINT                                  NOT NULL,
    category_id BIGINT                                  NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_product_category PRIMARY KEY (id)
);

-- changeset panch:1761085684742-11
CREATE TABLE product_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    url        TEXT                                    NOT NULL,
    is_main    BOOLEAN DEFAULT FALSE                   NOT NULL,
    extension  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_product_image PRIMARY KEY (id)
);

-- changeset panch:1761085684742-12
CREATE TABLE review
(
    review_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    rating     BIGINT                                  NOT NULL,
    comment    TEXT                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    product_id BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (review_id)
);

-- changeset panch:1761085684742-13
CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    external_id VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset panch:1761085684742-14
CREATE TABLE role_permissions
(
    granted_at    TIMESTAMP WITHOUT TIME ZONE,
    granted_by    VARCHAR(255),
    is_active     BOOLEAN NOT NULL,
    role_id       BIGINT  NOT NULL,
    permission_id BIGINT  NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id)
);

-- changeset panch:1761085684742-15
CREATE TABLE users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(255)                            NOT NULL,
    last_name        VARCHAR(255)                            NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    keycloak_user_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- changeset panch:1761085684742-16
ALTER TABLE orders
    ADD CONSTRAINT uc_orders_order_number UNIQUE (order_number);

-- changeset panch:1761085684742-17
ALTER TABLE permissions
    ADD CONSTRAINT uc_permissions_code UNIQUE (code);

-- changeset panch:1761085684742-18
ALTER TABLE role
    ADD CONSTRAINT uc_role_external UNIQUE (external_id);

-- changeset panch:1761085684742-19
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset panch:1761085684742-20
ALTER TABLE users
    ADD CONSTRAINT uc_users_keycloak_user UNIQUE (keycloak_user_id);

-- changeset panch:1761085684742-21
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset panch:1761085684742-22
ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset panch:1761085684742-23
ALTER TABLE attribute_option
    ADD CONSTRAINT FK_ATTRIBUTE_OPTION_ON_CATEGORY_ATTRIBUTE FOREIGN KEY (category_attribute_id) REFERENCES category_attribute (category_attribute_id);

-- changeset panch:1761085684742-24
ALTER TABLE category_attribute
    ADD CONSTRAINT FK_CATEGORY_ATTRIBUTE_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (category_id);

-- changeset panch:1761085684742-25
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (address_id);

-- changeset panch:1761085684742-26
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset panch:1761085684742-27
ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id);

-- changeset panch:1761085684742-28
ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset panch:1761085684742-29
ALTER TABLE product_attribute
    ADD CONSTRAINT FK_PRODUCT_ATTRIBUTE_ON_CATEGORY_ATTRIBUTE FOREIGN KEY (category_attribute_id) REFERENCES category_attribute (category_attribute_id);

-- changeset panch:1761085684742-30
ALTER TABLE product_attribute
    ADD CONSTRAINT FK_PRODUCT_ATTRIBUTE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset panch:1761085684742-31
ALTER TABLE product_category
    ADD CONSTRAINT FK_PRODUCT_CATEGORY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (category_id);

-- changeset panch:1761085684742-32
ALTER TABLE product_category
    ADD CONSTRAINT FK_PRODUCT_CATEGORY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset panch:1761085684742-33
ALTER TABLE product_image
    ADD CONSTRAINT FK_PRODUCT_IMAGE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset panch:1761085684742-34
ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset panch:1761085684742-35
ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset panch:1761085684742-36
ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissions (id);

-- changeset panch:1761085684742-37
ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

