-- liquibase formatted sql

-- changeset Francisco:1742961995073-1
CREATE TABLE address
(
    address_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street      VARCHAR(255),
    city        VARCHAR(255),
    country     VARCHAR(255),
    postal_code VARCHAR(255),
    user_id     BIGINT,
    CONSTRAINT pk_address PRIMARY KEY (address_id)
);

-- changeset Francisco:1742961995073-2
CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description TEXT                                    NOT NULL,
    is_active   BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

-- changeset Francisco:1742961995073-3
CREATE TABLE endpoint
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url          VARCHAR(255)                            NOT NULL,
    base_path    VARCHAR(255)                            NOT NULL,
    dynamic_path VARCHAR(255),
    http_method  VARCHAR(255)                            NOT NULL,
    is_public    BOOLEAN                                 NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_endpoint PRIMARY KEY (id)
);

-- changeset Francisco:1742961995073-4
CREATE TABLE order_item
(
    order_item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity          INTEGER,
    price_at_purchase DECIMAL,
    order_id          BIGINT,
    product_id        BIGINT,
    CONSTRAINT pk_order_item PRIMARY KEY (order_item_id)
);

-- changeset Francisco:1742961995073-5
CREATE TABLE orders
(
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number VARCHAR(255)                            NOT NULL,
    total_amount DECIMAL                                 NOT NULL,
    status       VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    address_id   BIGINT                                  NOT NULL,
    user_id      BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

-- changeset Francisco:1742961995073-6
CREATE TABLE product
(
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     TEXT,
    price           DECIMAL,
    stock_quantity  INTEGER,
    thumbnail_image VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    active          BOOLEAN,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

-- changeset Francisco:1742961995073-7
CREATE TABLE product_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id  BIGINT                                  NOT NULL,
    category_id BIGINT                                  NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_product_category PRIMARY KEY (id)
);

-- changeset Francisco:1742961995073-8
CREATE TABLE product_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    url        TEXT                                    NOT NULL,
    extension  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_product_image PRIMARY KEY (id)
);

-- changeset Francisco:1742961995073-9
CREATE TABLE review
(
    review_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    rating     BIGINT                                  NOT NULL,
    comment    TEXT                                    NOT NULL,
    user_id    BIGINT,
    product_id BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (review_id)
);

-- changeset Francisco:1742961995073-10
CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    external_id VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset Francisco:1742961995073-11
CREATE TABLE role_endpoint
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rol_id      BIGINT                                  NOT NULL,
    endpoint_id BIGINT                                  NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_role_endpoint PRIMARY KEY (id)
);

-- changeset Francisco:1742961995073-12
CREATE TABLE users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(255)                            NOT NULL,
    last_name        VARCHAR(255)                            NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    keycloak_user_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- changeset Francisco:1742961995073-13
ALTER TABLE orders
    ADD CONSTRAINT uc_orders_order_number UNIQUE (order_number);

-- changeset Francisco:1742961995073-14
ALTER TABLE role
    ADD CONSTRAINT uc_role_external UNIQUE (external_id);

-- changeset Francisco:1742961995073-15
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Francisco:1742961995073-16
ALTER TABLE users
    ADD CONSTRAINT uc_users_keycloak_user UNIQUE (keycloak_user_id);

-- changeset Francisco:1742961995073-17
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset Francisco:1742961995073-18
ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset Francisco:1742961995073-19
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (address_id);

-- changeset Francisco:1742961995073-20
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset Francisco:1742961995073-21
ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id);

-- changeset Francisco:1742961995073-22
ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset Francisco:1742961995073-23
ALTER TABLE product_category
    ADD CONSTRAINT FK_PRODUCT_CATEGORY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (category_id);

-- changeset Francisco:1742961995073-24
ALTER TABLE product_category
    ADD CONSTRAINT FK_PRODUCT_CATEGORY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset Francisco:1742961995073-25
ALTER TABLE product_image
    ADD CONSTRAINT FK_PRODUCT_IMAGE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset Francisco:1742961995073-26
ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset Francisco:1742961995073-27
ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset Francisco:1742961995073-28
ALTER TABLE role_endpoint
    ADD CONSTRAINT FK_ROLE_ENDPOINT_ON_ENDPOINT FOREIGN KEY (endpoint_id) REFERENCES endpoint (id);

-- changeset Francisco:1742961995073-29
ALTER TABLE role_endpoint
    ADD CONSTRAINT FK_ROLE_ENDPOINT_ON_ROL FOREIGN KEY (rol_id) REFERENCES role (id);

