-- liquibase formatted sql

-- changeset Francisco:1744252211154-1
CREATE TABLE attribute_option
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value                 VARCHAR(255),
    category_attribute_id BIGINT,
    CONSTRAINT pk_attribute_option PRIMARY KEY (id)
);

-- changeset Francisco:1744252211154-2
CREATE TABLE category_attribute
(
    category_attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                            NOT NULL,
    input_type            VARCHAR(255)                            NOT NULL,
    is_required           BOOLEAN,
    category_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_category_attribute PRIMARY KEY (category_attribute_id)
);

-- changeset Francisco:1744252211154-3
CREATE TABLE product_attribute
(
    product_attribute_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value                 VARCHAR(255)                            NOT NULL,
    product_id            BIGINT                                  NOT NULL,
    category_attribute_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_attribute PRIMARY KEY (product_attribute_id)
);

-- changeset Francisco:1744252211154-4
ALTER TABLE product_image
    ADD is_main BOOLEAN DEFAULT FALSE;

-- changeset Francisco:1744252211154-5
ALTER TABLE product_image
    ALTER COLUMN is_main SET NOT NULL;

-- changeset Francisco:1744252211154-6
ALTER TABLE attribute_option
    ADD CONSTRAINT FK_ATTRIBUTE_OPTION_ON_CATEGORY_ATTRIBUTE FOREIGN KEY (category_attribute_id) REFERENCES category_attribute (category_attribute_id);

-- changeset Francisco:1744252211154-7
ALTER TABLE category_attribute
    ADD CONSTRAINT FK_CATEGORY_ATTRIBUTE_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (category_id);

-- changeset Francisco:1744252211154-8
ALTER TABLE product_attribute
    ADD CONSTRAINT FK_PRODUCT_ATTRIBUTE_ON_CATEGORY_ATTRIBUTE FOREIGN KEY (category_attribute_id) REFERENCES category_attribute (category_attribute_id);

-- changeset Francisco:1744252211154-9
ALTER TABLE product_attribute
    ADD CONSTRAINT FK_PRODUCT_ATTRIBUTE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

-- changeset Francisco:1744252211154-10
ALTER TABLE product
    DROP COLUMN thumbnail_image;

