-- liquibase formatted sql

-- changeset Francisco:1737093375306-1
CREATE TABLE endpoint
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url         VARCHAR(255)                            NOT NULL,
    method_name VARCHAR(255)                            NOT NULL,
    http_method VARCHAR(255)                            NOT NULL,
    is_public   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_endpoint PRIMARY KEY (id)
);

-- changeset Francisco:1737093375306-2
CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    external_id VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset Francisco:1737093375306-3
CREATE TABLE role_endpoint
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rol_id      BIGINT                                  NOT NULL,
    endpoint_id BIGINT                                  NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_role_endpoint PRIMARY KEY (id)
);

-- changeset Francisco:1737093375306-4
ALTER TABLE role
    ADD CONSTRAINT uc_role_external UNIQUE (external_id);

-- changeset Francisco:1737093375306-5
ALTER TABLE role_endpoint
    ADD CONSTRAINT FK_ROLE_ENDPOINT_ON_ENDPOINT FOREIGN KEY (endpoint_id) REFERENCES endpoint (id);

-- changeset Francisco:1737093375306-6
ALTER TABLE role_endpoint
    ADD CONSTRAINT FK_ROLE_ENDPOINT_ON_ROL FOREIGN KEY (rol_id) REFERENCES role (id);

