name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Replace secrets in realm-export.json
        run: |
          jq '.identityProviders[].config.clientId = "${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" |
              .identityProviders[].config.clientSecret = "${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" |
              .smtpServer.password = "${{ secrets.GOOGLE_SMTP_PASSWORD }}" |
              .smtpServer.from = "${{ secrets.GOOGLE_SMTP_EMAIL }}" |
              .smtpServer.fromDisplayName = "${{ secrets.GOOGLE_SMTP_EMAIL }}" |
              .smtpServer.envelopeFrom = "${{ secrets.GOOGLE_SMTP_EMAIL }}" |
              .smtpServer.user = "${{ secrets.GOOGLE_SMTP_EMAIL }}"' ./src/test/resources/realm-base.json > ./src/test/resources/realm-export.json

      - name: Replace client secrets in application-test.yml
        run: |
          yq eval '.stripe.secret_key = "${{ secrets.STRIPE_API_KEY_TEST }}"' -i ./src/test/resources/application-test.yml

      - name: Grant execute permissions to Maven wrapper
        run: chmod +x ./mvnw

      - name: Run Tests with Maven
        run: ./mvnw verify --batch-mode

      - name: Build Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-spring-boot:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-spring-boot:${{ github.sha }}
