name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Replace client secrets in exported realm file
        run: |
          jq '.identityProviders[].config.clientId = "${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" |
              .identityProviders[].config.clientSecret = "${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" |
              .smtpServer.password = "${{ secrets.GOOGLE_SMTP_PASSWORD }}" |
              .smtpServer.from = "${{ secrets.GOOGLE_SMTP_EMAIL }}" |
              .smtpServer.fromDisplayName = "${{ secrets.GOOGLE_SMTP_EMAIL }}" |
              .smtpServer.envelopeFrom = "${{ secrets.GOOGLE_SMTP_EMAIL }}" |
              .smtpServer.user = "${{ secrets.GOOGLE_SMTP_EMAIL }}"' ./src/test/resources/realm-base.json > ./src/test/resources/realm-export.json

      - name: Grant execute permissions to Maven wrapper
        run: chmod +x ./mvnw

      - name: Running tests
        run: ./mvnw clean install test

      - name: Build Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-spring-boot:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-spring-boot:${{ github.sha }}
